# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  sampleapi:
    image: sampleapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - db
    networks:
      - my-network
  db:
    container_name: our-postgresql
    image: "postgres:latest"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Str0ngP@ssword
      POSTGRES_DB: my_postgres_db
    ports:
      - "7001:5432"
    volumes:
      - custompostgres:/var/lib/postgresql/data
    networks:
      - my-network
  migrations:
    build: .
    command: dotnet run --no-launch-profile
    environment:
      - RUN_MIGRATIONS=true
    depends_on:
      - db
volumes:
  custompostgres:
    
networks:
  my-network:
